#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Power")]
	public partial class LinqDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public LinqDbDataContext() : 
				base(global::TestTask.Properties.Settings.Default.PowerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ReqProc")]
		public ISingleResult<ReqProcResult> ReqProc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<ReqProcResult>)(result.ReturnValue));
		}
	}
	
	public partial class ReqProcResult
	{
		
		private System.Nullable<System.DateTime> _MeasureTime;
		
		private string _DeviceCode;
		
		private System.Nullable<double> _P;
		
		public ReqProcResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeasureTime", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> MeasureTime
		{
			get
			{
				return this._MeasureTime;
			}
			set
			{
				if ((this._MeasureTime != value))
				{
					this._MeasureTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceCode", DbType="VarChar(14)")]
		public string DeviceCode
		{
			get
			{
				return this._DeviceCode;
			}
			set
			{
				if ((this._DeviceCode != value))
				{
					this._DeviceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P", DbType="Float")]
		public System.Nullable<double> P
		{
			get
			{
				return this._P;
			}
			set
			{
				if ((this._P != value))
				{
					this._P = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
